console.log("===String Method===");
let str= "Welcome JavaScript";
console.log("Upper Case: ", str.toUpperCase());
console.log("Lower Case: ", str.toLowerCase());
console.log("Character at index 3: ", str.charAt(3));
console.log("Index of Java: ", str.indexOf("Java"));
let msg= "JavaScript is easy. JavaScript is powerful.";
console.log("Last index: ", msg.lastIndexOf("JavaScript"));
console.log("Slice: ", str.slice(0,7));
let res= msg.split(",");
console.log("Split: ", res);
let text= msg.replace("powerful", "hard");
console.log("Replace: ", text);
let f= "Hello";
let l= "World";
console.log("Concatenation: ",f.concat(" ", l));
console.log("===Include===");
let course= "JavaScript";
console.log(course.includes("Script"));
let num= [10, 20, 30, 40, 50];
console.log(num);
num.unshift(10);
console.log(num);
num.shift(10);
console.log(num);
let date= new Date();
console.log(date);
console.log("Year: ", date.getFullYear());
console.log("Month: ", date.getMonth());
console.log("Date: ", date.getDate());